Binary and hex files. Additional peripheral lib. Binary and hex files are now generated by Makefiles (nobody can load elf file directly in to processor). In stm32f429 peripheral library is lot of features which can by used for development. So Utilities are added in to compilation and stm32f429-discovery board specific features (as logging on display) are now possible. You can see STM32F429I-Discovery_FW_V1.0.1/Utilities/ for more details.

diff --git a/library-stm32f429/Makefile b/library-stm32f429/Makefile
--- a/library-stm32f429/Makefile
+++ b/library-stm32f429/Makefile
@@ -37,11 +37,24 @@ SOURCES := $(STM_COMMON)/Libraries/STM32F4xx_StdPeriph_Driver/src/misc.c \
 	$(STM_COMMON)/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c \
 	$(STM_COMMON)/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c \
 	$(STM_COMMON)/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c \
-	$(STM_COMMON)/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c
+	$(STM_COMMON)/Libraries/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c \
+	$(STM_COMMON)/Utilities/STM32F429I-Discovery/stm32f429i_discovery.c \
+	$(STM_COMMON)/Utilities/STM32F429I-Discovery/stm32f429i_discovery_i2c_ee.c \
+	$(STM_COMMON)/Utilities/STM32F429I-Discovery/stm32f429i_discovery_ioe.c \
+	$(STM_COMMON)/Utilities/STM32F429I-Discovery/stm32f429i_discovery_l3gd20.c \
+	$(STM_COMMON)/Utilities/STM32F429I-Discovery/stm32f429i_discovery_lcd.c \
+	$(STM_COMMON)/Utilities/STM32F429I-Discovery/stm32f429i_discovery_sdram.c \
+	$(STM_COMMON)/Utilities/Common/fonts.c \
+	$(STM_COMMON)/Utilities/Common/lcd_log.c
+
+
+
 
 OUTPUT_DIR = obj
 
 OBJ := $(patsubst $(STM_COMMON)/Libraries/STM32F4xx_StdPeriph_Driver/src/%.c,$(OUTPUT_DIR)/%.o, $(SOURCES))
+OBJ += $(patsubst $(STM_COMMON)/Utilities/STM32F429I-Discovery/%.c,$(OUTPUT_DIR)/%.o, $(SOURCES))
+OBJ += $(patsubst $(STM_COMMON)/Utilities/Common/%.c,$(OUTPUT_DIR)/%.o, $(SOURCES))
 
 LIBRARY_NAME := libstm32f429-periph.a
 
@@ -85,6 +98,57 @@ clean:
 
 # Implicit rules
 $(OUTPUT_DIR)/%.o : $(STM_COMMON)/Libraries/STM32F4xx_StdPeriph_Driver/src/%.c
+	@$(ECHO) -n "$(COLOR_BLUE)[CC] $< -> $@ ... "
+ifndef V
+	@$(CC) -c $(CFLAGS) $(CPPFLAGS) $< -o $@ 2> temp.log || touch temp.errors
+else
+	$(CC) -c $(CFLAGS) $(CPPFLAGS) $< -o $@ 2> temp.log || touch temp.errors
+endif
+	@if [ -e temp.errors ]; then \
+	    $(ECHO) "$(COLOR_RED)[ERRORS]:" 1>&2; \
+	    cat temp.log 1>&2; \
+	    $(ECHO) -n "$(COLOR_RESET)"; \
+	    rm -f temp.log temp.errors; \
+	    exit 1; \
+	elif [ -s temp.log ]; then \
+	    $(ECHO) "$(COLOR_YELLOW)[WARNINGS]:" 1>&2; \
+	    cat temp.log 1>&2; \
+	else \
+	    $(ECHO) "$(COLOR_GREEN) [OK]"; \
+	fi
+	@$(ECHO) -n "$(COLOR_RESET)"
+	@rm -f temp.log temp.errors
+
+
+
+# Implicit rules
+$(OUTPUT_DIR)/%.o : $(STM_COMMON)/Utilities/STM32F429I-Discovery/%.c
+	@$(ECHO) -n "$(COLOR_BLUE)[CC] $< -> $@ ... "
+ifndef V
+	@$(CC) -c $(CFLAGS) $(CPPFLAGS) $< -o $@ 2> temp.log || touch temp.errors
+else
+	$(CC) -c $(CFLAGS) $(CPPFLAGS) $< -o $@ 2> temp.log || touch temp.errors
+endif
+	@if [ -e temp.errors ]; then \
+	    $(ECHO) "$(COLOR_RED)[ERRORS]:" 1>&2; \
+	    cat temp.log 1>&2; \
+	    $(ECHO) -n "$(COLOR_RESET)"; \
+	    rm -f temp.log temp.errors; \
+	    exit 1; \
+	elif [ -s temp.log ]; then \
+	    $(ECHO) "$(COLOR_YELLOW)[WARNINGS]:" 1>&2; \
+	    cat temp.log 1>&2; \
+	else \
+	    $(ECHO) "$(COLOR_GREEN) [OK]"; \
+	fi
+	@$(ECHO) -n "$(COLOR_RESET)"
+	@rm -f temp.log temp.errors
+
+
+
+
+# Implicit rules
+$(OUTPUT_DIR)/%.o : $(STM_COMMON)/Utilities/Common/%.c
 	@$(ECHO) -n "$(COLOR_BLUE)[CC] $< -> $@ ... "
 ifndef V
 	@$(CC) -c $(CFLAGS) $(CPPFLAGS) $< -o $@ 2> temp.log || touch temp.errors
diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -12,22 +12,74 @@ OBJ := $(patsubst %.c,$(OUTPUT_DIR)/%.o, $(SOURCES))
 
 EXTERN_OBJ := ../hw-conf/obj/startup_stm32f429_439xx.o
 EXTERN_OBJ += ../hw-conf/obj/system_stm32f4xx.o
+EXTERN_OBJ += ../hw-conf/obj/syscalls.o
 
-BINARY_NAME := ../$(PROJ_NAME)
+ELF_NAME := ../$(PROJ_NAME)
+HEX_NAME := ../$(PROJ_NAME).hex
+BIN_NAME := ../$(PROJ_NAME).bin
+
+PROJECT_LIBS += -L$(PROJECT_PWD)/library-stm32f429/ -lstm32f429-periph
 
 
 
 .PHONY: all clean
 
-all: $(OUTPUT_DIR) $(BINARY_NAME)
+all: $(OUTPUT_DIR) $(ELF_NAME) $(HEX_NAME) $(BIN_NAME)
 
-$(BINARY_NAME): $(OBJ)
-	@$(ECHO) $(SOURCES)
+$(HEX_NAME) : $(ELF_NAME)
+	@$(ECHO) -n "$(COLOR_BLUE)[HEX-GEN] $< -> $@ ... "
+ifndef V
+	@$(OBJCOPY) -O ihex $(ELF_NAME) $(HEX_NAME) 2> temp.log || touch temp.errors
+else
+	$(OBJCOPY) -O ihex $(ELF_NAME) $(HEX_NAME) 2> temp.log || touch temp.errors
+endif
+	@if [ -e temp.errors ]; then \
+	    $(ECHO) "$(COLOR_RED)[ERRORS]:" 1>&2; \
+	    cat temp.log 1>&2; \
+	    $(ECHO) -n "$(COLOR_RESET)"; \
+	    rm -f temp.log temp.errors; \
+	    exit 1; \
+	elif [ -s temp.log ]; then \
+	    $(ECHO) "$(COLOR_YELLOW)[WARNINGS]:" 1>&2; \
+	    cat temp.log 1>&2; \
+	else \
+	    $(ECHO) "$(COLOR_GREEN) [OK]"; \
+	fi
+	@$(ECHO) -n "$(COLOR_RESET)"
+
+
+
+
+$(BIN_NAME) : $(ELF_NAME)
+	@$(ECHO) -n "$(COLOR_BLUE)[BIN-GEN] $< -> $@ ... "
+ifndef V
+	@$(OBJCOPY) -O binary $(ELF_NAME) $(BIN_NAME) 2> temp.log || touch temp.errors
+else
+	$(OBJCOPY) -O binary $(ELF_NAME) $(BIN_NAME) 2> temp.log || touch temp.errors
+endif
+	@if [ -e temp.errors ]; then \
+	    $(ECHO) "$(COLOR_RED)[ERRORS]:" 1>&2; \
+	    cat temp.log 1>&2; \
+	    $(ECHO) -n "$(COLOR_RESET)"; \
+	    rm -f temp.log temp.errors; \
+	    exit 1; \
+	elif [ -s temp.log ]; then \
+	    $(ECHO) "$(COLOR_YELLOW)[WARNINGS]:" 1>&2; \
+	    cat temp.log 1>&2; \
+	else \
+	    $(ECHO) "$(COLOR_GREEN) [OK]"; \
+	fi
+	@$(ECHO) -n "$(COLOR_RESET)"
+
+
+
+
+$(ELF_NAME): $(OBJ)
 	@$(ECHO) -n "$(COLOR_BLUE)[LD] $< -> $@ ... "
 ifndef V
-	@$(CC) $(COMMON_FLAGS) $(OBJ) $(EXTERN_OBJ) -o $@ $(LDFLAGS) 2> temp.log || touch temp.errors
+	@$(CC) $(COMMON_FLAGS) $(OBJ) $(EXTERN_OBJ) -o $@ $(LDFLAGS) $(PROJECT_LIBS) 2> temp.log || touch temp.errors
 else
-	$(CC) $(COMMON_FLAGS) $(OBJ) $(EXTERN_OBJ) -o $@ $(LDFLAGS) 2> temp.log || touch temp.errors
+	$(CC) $(COMMON_FLAGS) $(OBJ) $(EXTERN_OBJ) -o $@ $(LDFLAGS) $(PROJECT_LIBS) 2> temp.log || touch temp.errors
 endif
 	@if [ -e temp.errors ]; then \
 	    $(ECHO) "$(COLOR_RED)[ERRORS]:" 1>&2; \
@@ -53,6 +105,9 @@ clean:
 	@$(ECHO) "$(COLOR_BLUE)Cleaning $(COLOR_RESET)"
 	@$(RM) $(LIBRARY_NAME)
 	@$(RM) $(OUTPUT_DIR)
+	@$(RM) $(ELF_NAME)
+	@$(RM) $(BIN_NAME)
+	@$(RM) $(HEX_NAME)
 
 # Implicit rules
 $(OUTPUT_DIR)/%.o : %.c
